name = "PRISMA"
uuid = "7b67a8d2-c4f5-4933-b91c-0fc427024db5"
keywords = ["meta-analysis", "systematic review", "research", "PRISMA"]
license = "MIT"
desc = "Generate checklists and flow diagrams based on the Preferred Reporting Items for Systematic Reviews and Meta-Analyses (PRISMA) statement."
authors = "Ceco E. Maples <mapleselijah9@gmail.com>"
repo = "https://github.com/cecoeco/PRISMA.jl.git"
version = "0.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RPRMakie = "22d9f318-5e34-4b44-b769-6e3734a732a6"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]